// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dswvigrhjjjlhecxhayu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzd3ZpZ3JoampqbGhlY3hoYXl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMjcyMzQsImV4cCI6MjA1ODcwMzIzNH0.v29qbBVOkcAloevcnsV2ygbOdSJi9A2m5nlrpeYHuPw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);